---
title: "Oocyst prev and intensity analysis"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

 

```{r, message=FALSE}
library(lme4)
library(MASS)
library(ggplot2)
library(emmeans)
library(tidyverse)
library(glmmTMB)
library(car)
library(devtools)
library(cowplot)
library(broom.mixed)
library(brglm2)
```



```{r}
WARP <- read.csv("/Users/virginiahowick/Documents/allelic_replacement/Lah_TransmissionProject_Dataset_25Apr25/WARP/WARP_table_oocyst_4Aug25_normalised_2clones.csv")
HSP101 <- read.csv("/Users/virginiahowick/Documents/allelic_replacement/Oocyst_all_genes/HSP101_table_oocyst_normalised_19Mar25.csv")
Pfs47 <- read.csv("/Users/virginiahowick/Documents/allelic_replacement/Oocyst_all_genes/P47_table_oocyst_normalisedOocyst_19Mar25.csv")
CTRP <- read.csv("/Users/virginiahowick/Documents/allelic_replacement/Lah_TransmissionProject_Dataset_25Apr25/CTRP/CTRP_table_oocyst_normalised_20Mar25.csv")
Pfs25 <- read.csv("/Users/virginiahowick/Documents/allelic_replacement/Oocyst_all_genes/Pfs25_table_oocyst_17Mar25_normalised.csv")

WARP <- WARP[ , 1:9]
HSP101 <- HSP101[ , 1:9]
Pfs47 <- Pfs47[ , 1:9]
Pfs25 <- Pfs25[ , 1:9]
CTRP <- CTRP[ , 1:9]

WARP$gene <- rep("WARP", length(WARP$name))
HSP101$gene <- rep("HSP101", length(HSP101$name))
Pfs47$gene <- rep("Pfs47", length(Pfs47$name))
Pfs25$gene <- rep("Pfs25", length(Pfs25$name))
CTRP$gene <- rep("CTRP", length(CTRP$name))

CTRP <- subset(CTRP, background!="HB3")
CTRP <- subset(CTRP, clone!="bulk")

CTRP$RefAlt <- ifelse(CTRP$allele == "D", "Ref", "Alt")
HSP101$RefAlt <- ifelse(HSP101$allele == "R", "Ref", "Alt")
Pfs25$RefAlt <- ifelse(Pfs25$allele == "G", "Ref", "Alt")
Pfs47$RefAlt <- ifelse(Pfs47$allele == "S", "Ref", "Alt")
WARP$RefAlt <- ifelse(WARP$allele == "F", "Ref", "Alt")

alldata <- rbind(CTRP, HSP101, Pfs25, Pfs47, WARP)

write.csv(alldata, file="oocysts_20260416.csv")
```


Look at 3D7 prev in Kisumu as control and add to all data as a potential factor in the model
```{r}
alldata <- alldata %>%
  group_by(gene, rep) %>%
  mutate(
    prevalence_3D7 = {
      use <- mosquito == "An_gam" & clone == "3D7"   # change clone->background if needed
      n_tot <- sum(use, na.rm = TRUE)
      n_pos <- sum((oocysts > 0) & use, na.rm = TRUE)
      ifelse(n_tot > 0, n_pos / n_tot, NA_real_)
    }
  ) %>%
  ungroup()

prev3d7 <- alldata %>%
  group_by(gene, rep) %>%
  mutate(
    prevalence_3D7 = {
      use <- mosquito == "An_gam" & clone == "3D7"   # change clone->background if needed
      n_tot <- sum(use, na.rm = TRUE)
      n_pos <- sum((oocysts > 0) & use, na.rm = TRUE)
      ifelse(n_tot > 0, n_pos / n_tot, NA_real_)
    }
  )

prev3d7$rep <- as.factor(prev3d7$rep)


prev_plotdat <- prev3d7 %>%
  distinct(gene, rep, prevalence_3D7) %>%
  filter(!is.na(prevalence_3D7))

genes <- c("HSP101","Pfs25","Pfs47","WARP","CTRP")
prev_plotdat <- prev_plotdat %>% filter(gene %in% genes)

ggplot(prev_plotdat, aes(x = factor(rep), y = prevalence_3D7, fill = gene)) +
  geom_col(width = 0.75, color = "black", linewidth = 0.2) +
  geom_text(aes(label = round(prevalence_3D7, 2)), 
            vjust = -0.4, size = 3) +
  facet_grid(. ~ gene, scales = "free_x", space = "free_x", switch = "x") +
  scale_y_continuous(limits = c(0, 1), expand = expansion(mult = c(0, 0.05))) +
  labs(
    x = "Replicate",
    y = "3D7 prevalence (An. gam.)",
    title = NULL
  ) +
  theme_classic(base_size = 12) +
  theme(
    panel.spacing.x = unit(1, "lines"),
    strip.background = element_blank(),
    strip.placement = "outside",
    strip.text = element_text(face = "bold"),
    legend.position = "none",
    axis.text.x = element_text(size = 9)
  )

```

Subset data and set as factors

```{r}

alldata <- subset(alldata, clone!="3D7")
alldata <- subset(alldata, clone!="HB3")
alldata$background[alldata$background == "3D25"] <- "3D7"

alldata$clone<-as.factor(alldata$clone)
alldata$allele<-as.factor(alldata$allele)
alldata$rep<-as.factor(alldata$rep)
alldata$mosquito<-as.factor(alldata$mosquito)
alldata$RefAlt <- factor(alldata$RefAlt, levels = c("Ref","Alt"), ordered = TRUE)

summary(alldata$oocysts)
var(alldata$oocysts)

alldata$oocyst_prev <- rep(0, length(alldata$name))
alldata[which(alldata$oocysts > 0), ]$oocyst_prev <- 1

alldata$mosq_allele <- interaction(alldata$mosquito,
                                           alldata$allele,
                                           sep = "_")

alldata$symp <- rep("symp", length(alldata$mosquito))
alldata[which(alldata$mosquito == "An_gam"), ]$symp <- "allo"
alldata$symp[alldata$mosquito == "An_alb" & !(alldata$gene %in% c("CTRP", "Pfs47")) ] <- "allo"
alldata[which(alldata$gene == "Pfs47" & alldata$mosquito != "An_alb"), ]$symp <- "allo"

```

Plot graph from raw data

```{r}
#noctrp <- subset(alldata, alldata$gene !="CTRP")
#noctrp <- subset(noctrp, noctrp$mosquito!="An_alb")


# The genes you want to loop over
genes_to_plot <- c("CTRP", "HSP101", "Pfs25", "Pfs47", "WARP")

# Make plots for each gene
plots <- lapply(genes_to_plot, function(g) {
  ggplot(data = filter(alldata, gene == g), aes(x = RefAlt, y = oocysts)) + 
    geom_violin(size = 0.4) + 
    geom_jitter(width = 0.2, height = 0.2, aes(color = RefAlt), size = 0.7, alpha = 0.7) +
    scale_y_continuous(
      limits = c(0, NA),
      oob = scales::oob_squish_any,  
      expand = expansion(mult = c(0, .05))
    ) +
  scale_x_discrete(
    labels = c("Ref" = "Ref", "Alt" = "Alt")
  ) +
    facet_grid(. ~ mosquito, labeller = labeller(
      mosquito = c(
        "An_gam"   = "gambiae",
        "An_steph" = "stephensi",
        "An_mini"  = "minimus",
        "An_alb"   = "albimanus"
      )
    )) + 
    theme_bw(base_size = 6) +
    theme(
      axis.line = element_line(colour = "black", size = 0.3, linetype = "solid"), 
      strip.background = element_rect(fill = "white", color = "black"), 
      strip.text = element_text(face = "italic", size = 3.5),
      axis.text = element_text(size = 6),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "none",
      axis.ticks.length = unit(0.1, "cm")
    ) +
    scale_colour_manual(values = c("#E31A1C","#6A3D9A")) 
    #ggtitle(g)   # Add gene name as title
})

# Access a specific plot
plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]
plots[[5]]


pdf("/Users/virginiahowick/Documents/allelic_replacement/plots/rawdataoocysts_20260416.pdf", width = 8, height = 1.6)
plot_grid(plotlist = plots, ncol = 5)
dev.off()
```

Calculate N and prop infected to place below raw data plots
```{r}
prop_infected <- alldata %>%
  group_by(mosquito, gene, RefAlt) %>%
  summarise(
    n_total      = n(),
    n_infected   = sum(oocyst_prev, na.rm = TRUE),
    prop_infected = mean(oocyst_prev, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    pct_infected = round(prop_infected * 100, 1)  # one decimal place
  )

prop_infected

write.csv(prop_infected, file="/Users/virginiahowick/Documents/allelic_replacement/analysis/oocyst_prevs_20260416.csv")
```

Run oocyst prev model and calculate emmeans

```{r}

# List of genes to loop over
genes <- c("CTRP", "HSP101", "Pfs25", "Pfs47", "WARP")


results <- lapply(genes, function(g) {
  
  df <- subset(alldata, gene == g)   
  
  mod <- glm(
    oocyst_prev ~ RefAlt * mosquito + rep,
    family = binomial(link = "logit"),
    data = df,
    method = "brglmFit"
    )
  
  # Tidy summary (fixed effects only)
  sum_df <- broom.mixed::tidy(mod, effects = "fixed") %>%
    mutate(gene = g)
  
  # ANOVA table
  anova_tab <- Anova(mod, type = "III")
  anova_df <- as.data.frame(anova_tab) %>%
    rownames_to_column("term") %>%
    mutate(gene = g)
  
 # EMMeans + contrasts
  emm_tab <- emmeans(mod, specs = pairwise ~ RefAlt | mosquito, type = "response")
  
  emm_df <- as.data.frame(emm_tab$emmeans) %>%
    mutate(gene = g)
  
  contrast_df <- as.data.frame(emm_tab$contrasts) %>%
    mutate(gene = g)
  
  list(summary = sum_df, anova = anova_df, emm = emm_df, contrasts = contrast_df)
})

# Combine across genes
summary_all   <- bind_rows(lapply(results, `[[`, "summary"))
anova_all     <- bind_rows(lapply(results, `[[`, "anova"))
emm_all       <- bind_rows(lapply(results, `[[`, "emm"))
contrasts_all <- bind_rows(lapply(results, `[[`, "contrasts"))

# Export to CSV
write.csv(summary_all,   "prev_summary_all_20260416.csv",   row.names = FALSE)
write.csv(anova_all,     "prev_anova_all_20260416.csv",     row.names = FALSE)
write.csv(emm_all,       "prev_emm_all_20260416.csv",       row.names = FALSE)
write.csv(contrasts_all, "prev_contrasts_all_20260416.csv", row.names = FALSE)

summary_all
anova_all
emm_all
contrasts_all

```


Now make the EMM prev plots
```{r}


emm_all$symp <- rep("symp", length(emm_all$mosquito))
emm_all[which(emm_all$mosquito == "An_gam"), ]$symp <- "allo"
emm_all$symp[emm_all$mosquito == "An_alb" & !(emm_all$gene %in% c("CTRP", "Pfs47")) ] <- "allo"
emm_all[which(emm_all$gene == "Pfs47" & emm_all$mosquito != "An_alb"), ]$symp <- "allo"



emm_plots <- emm_all %>%
  group_split(gene) %>%
  setNames(unique(emm_all$gene)) %>%
  lapply(function(df) {
    ggplot(df, aes(x = RefAlt, y = prob, group = mosquito, color = mosquito, shape=symp)) + 
      geom_point(size = 1.3) + 
      geom_line(size = 0.55) +
      geom_ribbon(
        aes(ymin = prob - SE, ymax = prob + SE, fill = mosquito),
        alpha = 0.3
      ) +
      theme_classic(base_size = 6) + 
      scale_fill_manual(values = c(
        "An_gam"   = "#ECC671",
        "An_mini"  = "#7CB599",
        "An_steph" = "#D5ABC6",
        "An_alb"   = "#1F78B4"
      )) +
      scale_colour_manual(values = c(
        "An_gam"   = "#ECC671",
        "An_mini"  = "#7CB599",
        "An_steph" = "#D5ABC6",
        "An_alb"   = "#1F78B4"
      )) +
      scale_x_discrete(expand = expansion(mult = c(0.2, 0.2))) +
      theme(
        legend.position = "none",
        axis.title.x    = element_blank(),
        axis.title.y    = element_blank(),
        axis.text       = element_text(size = 6),
        axis.ticks.length = unit(0.1, "cm")
      ) 
      #ggtitle(unique(df$gene))   # Add gene title
  })

emm_plots[["CTRP"]]
emm_plots[["HSP101"]]
emm_plots[["Pfs25"]]
emm_plots[["Pfs47"]]
emm_plots[["WARP"]]

pdf("/Users/virginiahowick/Documents/allelic_replacement/plots/prev_oocysts_20260416.pdf", width = 8, height = 1.6)
plot_grid(plotlist = emm_plots, ncol = 5)
dev.off()
```


Now do stats and plots for Oocyst Intensity
```{r}
oocysts_nozeros <- subset(alldata, alldata$oocysts > 0)
#Pfs25 <- subset(oocysts_nozeros, oocysts_nozeros$gene=="Pfs25")

genes <- c("CTRP", "HSP101", "Pfs25", "Pfs47", "WARP")

results <- lapply(genes, function(g) {
  
  df <- subset(oocysts_nozeros, gene == g)   # adjust if data frame has a different name
  
  # Choose formula depending on gene
  
  if (g %in% c("CTRP", "WARP")) {
    form <- oocysts ~ RefAlt * mosquito + (1 | rep) + (1 | clone)
  } else {
    form <- oocysts ~ RefAlt * mosquito + (1 | rep)
  }
  
# Fit model
  mod <- glmmTMB(
    form,
    family = nbinom2,
    data = df
  )
  
  # Tidy summary (fixed effects only)
  sum_df <- broom.mixed::tidy(mod, effects = "fixed") %>%
    mutate(gene = g)
  
  # ANOVA table
  anova_tab <- Anova(mod, type = "III")
  anova_df <- as.data.frame(anova_tab) %>%
    rownames_to_column("term") %>%
    mutate(gene = g)
  
 # EMMeans + contrasts
  emm_tab <- emmeans(mod, specs = pairwise ~ RefAlt | mosquito, type = "response")
  
  emm_df <- as.data.frame(emm_tab$emmeans) %>%
    mutate(gene = g)
  
  contrast_df <- as.data.frame(emm_tab$contrasts) %>%
    mutate(gene = g)
  
  list(summary = sum_df, anova = anova_df, emm = emm_df, contrasts = contrast_df)
})

# Combine across genes
summary_all   <- bind_rows(lapply(results, `[[`, "summary"))
anova_all     <- bind_rows(lapply(results, `[[`, "anova"))
emm_all       <- bind_rows(lapply(results, `[[`, "emm"))
contrasts_all <- bind_rows(lapply(results, `[[`, "contrasts"))

# Export to CSV
write.csv(summary_all,   "int_summary_all_20260416.csv",   row.names = FALSE)
write.csv(anova_all,     "int_anova_all_20260416.csv",     row.names = FALSE)
write.csv(emm_all,       "int_emm_all_20260416.csv",       row.names = FALSE)
write.csv(contrasts_all, "int_contrasts_all_20260416.csv", row.names = FALSE)

summary_all
anova_all
emm_all
contrasts_all

```

Now make the EMM Intensity plots
```{r}


emm_all$symp <- rep("symp", length(emm_all$mosquito))
emm_all[which(emm_all$mosquito == "An_gam"), ]$symp <- "allo"
emm_all[which(emm_all$gene == "Pfs47"), ]$symp <- "allo"


emm_plots <- emm_all %>%
  group_split(gene) %>%
  setNames(unique(emm_all$gene)) %>%
  lapply(function(df) {
    ggplot(df, aes(x = RefAlt, y = response, group = mosquito, color = mosquito, shape=symp)) + 
      geom_point(size = 1.3) + 
      geom_line(size = 0.55) +
      geom_ribbon(
        aes(ymin = response - SE, ymax = response + SE, fill = mosquito),
        alpha = 0.3
      ) +
      theme_classic(base_size = 6) + 
      scale_fill_manual(values = c(
        "An_gam"   = "#ECC671",
        "An_mini"  = "#7CB599",
        "An_steph" = "#D5ABC6",
        "An_alb"   = "#1F78B4"
      )) +
      scale_colour_manual(values = c(
        "An_gam"   = "#ECC671",
        "An_mini"  = "#7CB599",
        "An_steph" = "#D5ABC6",
        "An_alb"   = "#1F78B4"
      )) +
      scale_x_discrete(expand = expansion(mult = c(0.2, 0.2))) +
      theme(
        legend.position = "none",
        axis.title.x    = element_blank(),
        axis.title.y    = element_blank(),
        axis.text       = element_text(size = 6),
        axis.ticks.length = unit(0.1, "cm")
      ) 
      #ggtitle(unique(df$gene))   # Add gene title
  })

emm_plots[["CTRP"]]
emm_plots[["HSP101"]]
emm_plots[["Pfs25"]]
emm_plots[["Pfs47"]]
emm_plots[["WARP"]]

pdf("/Users/virginiahowick/Documents/allelic_replacement/plots/intensity_oocysts_20260416.pdf", width = 8, height = 1.6)
plot_grid(plotlist = emm_plots, ncol = 5)
dev.off()
```

```{r}
session_info()
```

